// Package store is mcphub's local intelligence layer: a single-file SQLite
// database (driven by the pure-Go modernc.org/sqlite, so no cgo) that records
// every proxied tool call, every sync operation, and which servers mcphub has
// written into which agent harness.
//
// The typed query layer under internal/store/db is generated by sqlc from the
// SQL in migrations/ and queries/. This file is the hand-written ergonomic
// wrapper the rest of mcphub talks to.
package store

import (
	"context"
	"database/sql"
	"embed"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	_ "modernc.org/sqlite"

	"github.com/abdul-hamid-achik/mcphub/internal/store/db"
)

//go:embed migrations/*.sql
var migrationsFS embed.FS

// Store wraps the SQLite connection and the sqlc-generated queries.
type Store struct {
	sql *sql.DB
	q   *db.Queries
}

// DefaultPath is where the intelligence DB lives unless overridden. It follows
// the XDG data convention (~/.local/share/mcphub/mcphub.db).
func DefaultPath() string {
	if dir := os.Getenv("MCPHUB_DB"); dir != "" {
		return dir
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "mcphub.db"
	}
	return filepath.Join(home, ".local", "share", "mcphub", "mcphub.db")
}

// Open opens (creating if needed) the SQLite database at path and applies all
// embedded migrations. A path of ":memory:" yields an ephemeral in-memory DB,
// which the tests use.
func Open(path string) (*Store, error) {
	if path != ":memory:" {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return nil, fmt.Errorf("create db dir: %w", err)
		}
	}
	// busy_timeout keeps concurrent gateway writes from failing under load.
	dsn := path + "?_pragma=busy_timeout(5000)&_pragma=journal_mode(WAL)&_pragma=foreign_keys(on)"
	sqlDB, err := sql.Open("sqlite", dsn)
	if err != nil {
		return nil, fmt.Errorf("open sqlite: %w", err)
	}
	// SQLite serializes writes; a single connection prevents "database is
	// locked" errors under concurrent gateway writes. For :memory: this is
	// also required so migrations and queries share the same per-connection db.
	sqlDB.SetMaxOpenConns(1)
	if err := applyMigrations(sqlDB); err != nil {
		sqlDB.Close()
		return nil, err
	}
	return &Store{sql: sqlDB, q: db.New(sqlDB)}, nil
}

func applyMigrations(sqlDB *sql.DB) error {
	entries, err := migrationsFS.ReadDir("migrations")
	if err != nil {
		return fmt.Errorf("read migrations: %w", err)
	}
	names := make([]string, 0, len(entries))
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".sql") {
			names = append(names, e.Name())
		}
	}
	sort.Strings(names)
	for _, name := range names {
		body, err := migrationsFS.ReadFile("migrations/" + name)
		if err != nil {
			return fmt.Errorf("read migration %s: %w", name, err)
		}
		if _, err := sqlDB.Exec(string(body)); err != nil {
			return fmt.Errorf("apply migration %s: %w", name, err)
		}
	}
	return nil
}

// Close closes the underlying database.
func (s *Store) Close() error { return s.sql.Close() }

// --- tool-call telemetry --------------------------------------------------

// CallRecord describes a single proxied tool invocation to be persisted.
type CallRecord struct {
	Server      string
	Tool        string
	Namespaced  string
	Duration    time.Duration
	Err         error
	ArgsBytes   int
	ResultBytes int
}

// estTokens is a deliberately cheap heuristic: roughly four bytes per token.
// It is good enough to compare the relative context cost of servers/tools.
func estTokens(argsBytes, resultBytes int) int64 {
	return int64((argsBytes + resultBytes) / 4)
}

// RecordCall persists one proxied tool call. Errors are swallowed into the
// returned error but never block the proxy path (callers log-and-continue).
func (s *Store) RecordCall(ctx context.Context, rec CallRecord) error {
	errStr := ""
	if rec.Err != nil {
		errStr = rec.Err.Error()
	}
	return s.q.InsertToolCall(ctx, db.InsertToolCallParams{
		Ts:          time.Now().UTC().Format(time.RFC3339Nano),
		Server:      rec.Server,
		Tool:        rec.Tool,
		Namespaced:  rec.Namespaced,
		DurationMs:  rec.Duration.Milliseconds(),
		Ok:          rec.Err == nil,
		Error:       errStr,
		ArgsBytes:   int64(rec.ArgsBytes),
		ResultBytes: int64(rec.ResultBytes),
		EstTokens:   estTokens(rec.ArgsBytes, rec.ResultBytes),
	})
}

// Totals is the all-time rollup surfaced by `mcphub stats`.
type Totals struct {
	Calls     int64 `json:"calls"`
	EstTokens int64 `json:"est_tokens"`
	TotalMs   int64 `json:"total_ms"`
	Errors    int64 `json:"errors"`
}

// allTimeCutoff is older than any real RFC3339 timestamp, so `WHERE ts >= ?`
// with it includes every row. RFC3339 strings sort lexicographically by time.
const allTimeCutoff = "0001-01-01T00:00:00Z"

// cutoff returns the RFC3339 lower bound for a lookback window. A non-positive
// duration means all time.
func cutoff(since time.Duration) string {
	if since <= 0 {
		return allTimeCutoff
	}
	return time.Now().UTC().Add(-since).Format(time.RFC3339Nano)
}

// Totals returns the all-time call count, token estimate, and error count.
func (s *Store) Totals(ctx context.Context) (Totals, error) { return s.TotalsSince(ctx, 0) }

// TotalsSince returns the rollup for calls within the last `since` window
// (0 = all time).
func (s *Store) TotalsSince(ctx context.Context, since time.Duration) (Totals, error) {
	row, err := s.q.TotalStats(ctx, cutoff(since))
	if err != nil {
		return Totals{}, err
	}
	return Totals{
		Calls:     row.Calls,
		EstTokens: asInt64(row.EstTokens),
		TotalMs:   asInt64(row.TotalMs),
		Errors:    asInt64(row.Errors),
	}, nil
}

// ServerStat is per-server usage, sorted by call count descending.
type ServerStat struct {
	Server    string `json:"server"`
	Calls     int64  `json:"calls"`
	Errors    int64  `json:"errors"`
	EstTokens int64  `json:"est_tokens"`
	AvgMs     int64  `json:"avg_ms"`
}

// ServerStats returns per-server usage statistics (all time).
func (s *Store) ServerStats(ctx context.Context) ([]ServerStat, error) {
	return s.ServerStatsSince(ctx, 0)
}

// ServerStatsSince returns per-server usage within the last `since` window.
func (s *Store) ServerStatsSince(ctx context.Context, since time.Duration) ([]ServerStat, error) {
	rows, err := s.q.ServerStats(ctx, cutoff(since))
	if err != nil {
		return nil, err
	}
	out := make([]ServerStat, 0, len(rows))
	for _, r := range rows {
		out = append(out, ServerStat{
			Server:    r.Server,
			Calls:     r.Calls,
			Errors:    asInt64(r.Errors),
			EstTokens: asInt64(r.EstTokens),
			AvgMs:     r.AvgMs,
		})
	}
	return out, nil
}

// ToolStat is per-tool usage, sorted by call count descending.
type ToolStat struct {
	Server    string `json:"server"`
	Tool      string `json:"tool"`
	Calls     int64  `json:"calls"`
	Errors    int64  `json:"errors"`
	AvgMs     int64  `json:"avg_ms"`
	EstTokens int64  `json:"est_tokens"`
}

// ToolStats returns per-tool usage statistics (all time).
func (s *Store) ToolStats(ctx context.Context) ([]ToolStat, error) {
	return s.ToolStatsSince(ctx, 0)
}

// ToolStatsSince returns per-tool usage within the last `since` window.
func (s *Store) ToolStatsSince(ctx context.Context, since time.Duration) ([]ToolStat, error) {
	rows, err := s.q.ToolCallStats(ctx, cutoff(since))
	if err != nil {
		return nil, err
	}
	out := make([]ToolStat, 0, len(rows))
	for _, r := range rows {
		out = append(out, ToolStat{
			Server:    r.Server,
			Tool:      r.Tool,
			Calls:     r.Calls,
			Errors:    asInt64(r.Errors),
			AvgMs:     r.AvgMs,
			EstTokens: asInt64(r.EstTokens),
		})
	}
	return out, nil
}

// RecentCalls returns the most recent n tool calls (newest first).
func (s *Store) RecentCalls(ctx context.Context, n int) ([]db.ToolCall, error) {
	return s.q.RecentToolCalls(ctx, int64(n))
}

// --- managed-entry bookkeeping & sync audit -------------------------------

// SetManaged replaces the full set of mcphub-managed servers for an agent. The
// clear-and-reinsert runs in a single transaction so a mid-loop failure can't
// partially wipe the owned set (which would let the next sync miss removals).
func (s *Store) SetManaged(ctx context.Context, agent string, servers []string) error {
	tx, err := s.sql.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("begin tx: %w", err)
	}
	defer tx.Rollback() // no-op after commit
	q := s.q.WithTx(tx)
	if err := q.ClearManagedForAgent(ctx, agent); err != nil {
		return fmt.Errorf("clear managed: %w", err)
	}
	now := time.Now().UTC().Format(time.RFC3339Nano)
	for _, srv := range servers {
		if err := q.UpsertManaged(ctx, db.UpsertManagedParams{Agent: agent, Server: srv, AppliedAt: now}); err != nil {
			return fmt.Errorf("upsert managed %q: %w", srv, err)
		}
	}
	return tx.Commit()
}

// ManagedFor returns the server names mcphub currently manages for an agent.
func (s *Store) ManagedFor(ctx context.Context, agent string) ([]string, error) {
	rows, err := s.q.ListManagedForAgent(ctx, agent)
	if err != nil {
		return nil, err
	}
	out := make([]string, 0, len(rows))
	for _, r := range rows {
		out = append(out, r.Server)
	}
	return out, nil
}

// LogSync appends a row to the sync audit log.
func (s *Store) LogSync(ctx context.Context, agent, mode string, servers []string, dryRun bool) error {
	return s.q.InsertSyncRun(ctx, db.InsertSyncRunParams{
		Ts:      time.Now().UTC().Format(time.RFC3339Nano),
		Agent:   agent,
		Mode:    mode,
		Servers: strings.Join(servers, ","),
		DryRun:  dryRun,
	})
}

// asInt64 coerces sqlc's interface{} aggregate columns (COALESCE/SUM defeat
// its type inference under SQLite) into a plain int64. modernc returns int64
// for integer SUMs and float64 for averaged/real values; both are handled.
func asInt64(v interface{}) int64 {
	switch n := v.(type) {
	case int64:
		return n
	case int:
		return int64(n)
	case float64:
		return int64(n)
	case nil:
		return 0
	default:
		return 0
	}
}
