// Package store is mcphub's local intelligence layer: a single-file SQLite
// database (driven by the pure-Go modernc.org/sqlite, so no cgo) that records
// every proxied tool call, every sync operation, and which servers mcphub has
// written into which agent harness.
//
// The typed query layer under internal/store/db is generated by sqlc from the
// SQL in migrations/ and queries/. This file is the hand-written ergonomic
// wrapper the rest of mcphub talks to.
package store

import (
	"context"
	"crypto/rand"
	"database/sql"
	"embed"
	"encoding/hex"
	"errors"
	"fmt"
	"github.com/abdul-hamid-achik/mcphub/internal/store/db"
	_ "modernc.org/sqlite"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"
)

//go:embed migrations/*.sql
var migrationsFS embed.FS

// Store wraps the SQLite connection and the sqlc-generated queries.
type Store struct {
	sql        *sql.DB
	q          *db.Queries
	now        func() time.Time
	stopPruner chan struct{}
	pruneNow   chan chan struct{}
	prunerDone chan struct{}
	closeOnce  sync.Once
	closeErr   error
}

// DefaultPath is where the intelligence DB lives unless overridden. It follows
// the XDG data convention (~/.local/share/mcphub/mcphub.db).
func DefaultPath() string {
	if dir := os.Getenv("MCPHUB_DB"); dir != "" {
		return dir
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "mcphub.db"
	}
	return filepath.Join(home, ".local", "share", "mcphub", "mcphub.db")
}

// Open opens (creating if needed) the SQLite database at path and applies all
// embedded migrations. A path of ":memory:" yields an ephemeral in-memory DB,
// which the tests use.
func Open(path string) (*Store, error) {
	if path != ":memory:" {
		dir := filepath.Dir(path)
		_, statErr := os.Stat(dir)
		if statErr != nil && !errors.Is(statErr, os.ErrNotExist) {
			return nil, fmt.Errorf("inspect db dir: %w", statErr)
		}
		if err := os.MkdirAll(dir, 0o700); err != nil {
			return nil, fmt.Errorf("create db dir: %w", err)
		}
		if errors.Is(statErr, os.ErrNotExist) {
			if err := os.Chmod(dir, 0o700); err != nil {
				return nil, fmt.Errorf("secure db dir: %w", err)
			}
		}
	}
	// busy_timeout keeps concurrent gateway writes from failing under load.
	dsn := path + "?_pragma=busy_timeout(5000)&_pragma=journal_mode(WAL)&_pragma=foreign_keys(on)"
	sqlDB, err := sql.Open("sqlite", dsn)
	if err != nil {
		return nil, fmt.Errorf("open sqlite: %w", err)
	}
	// SQLite serializes writes; a single connection prevents "database is
	// locked" errors under concurrent gateway writes. For :memory: this is
	// also required so migrations and queries share the same per-connection db.
	sqlDB.SetMaxOpenConns(1)
	if err := applyMigrations(sqlDB); err != nil {
		sqlDB.Close()
		return nil, err
	}
	if path != ":memory:" {
		for _, candidate := range []string{path, path + "-wal", path + "-shm"} {
			if err := os.Chmod(candidate, 0o600); err != nil && !errors.Is(err, os.ErrNotExist) {
				sqlDB.Close()
				return nil, fmt.Errorf("secure db file %s: %w", filepath.Base(candidate), err)
			}
		}
	}
	st := &Store{
		sql: sqlDB, q: db.New(sqlDB), now: time.Now,
		stopPruner: make(chan struct{}), pruneNow: make(chan chan struct{}), prunerDone: make(chan struct{}),
	}
	// Expired result payloads are disposable. Pruning is best-effort so a
	// cleanup failure never makes the telemetry database unavailable.
	_ = st.pruneExpired(context.Background())
	go st.runPruner()
	return st, nil
}

func applyMigrations(sqlDB *sql.DB) error {
	entries, err := migrationsFS.ReadDir("migrations")
	if err != nil {
		return fmt.Errorf("read migrations: %w", err)
	}
	names := make([]string, 0, len(entries))
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".sql") {
			names = append(names, e.Name())
		}
	}
	sort.Strings(names)
	for _, name := range names {
		body, err := migrationsFS.ReadFile("migrations/" + name)
		if err != nil {
			return fmt.Errorf("read migration %s: %w", name, err)
		}
		if _, err := sqlDB.Exec(string(body)); err != nil {
			return fmt.Errorf("apply migration %s: %w", name, err)
		}
	}
	return nil
}

// Close closes the underlying database.
func (s *Store) Close() error {
	s.closeOnce.Do(func() {
		close(s.stopPruner)
		<-s.prunerDone
		s.closeErr = s.sql.Close()
	})
	return s.closeErr
}

const (
	resultTTL           = 24 * time.Hour
	resultPruneInterval = time.Hour
	spoolTimeFormat     = "2006-01-02T15:04:05.000000000Z"
)

var (
	// ErrResultNotFound means the call ID is unknown (or was already pruned).
	ErrResultNotFound = errors.New("spooled result not found")
	// ErrResultExpired means the call ID exists but its fixed retention window
	// has elapsed.
	ErrResultExpired = errors.New("spooled result expired")
	// ErrResultCursorOutOfRange means the zero-based cursor is negative or
	// beyond the payload. A cursor exactly at totalBytes is a valid empty final
	// page.
	ErrResultCursorOutOfRange = errors.New("result cursor out of range")
)

// ResultPage is one bounded byte range from a complete serialized MCP result.
// Cursor and NextCursor are zero-based byte offsets into the stored payload.
type ResultPage struct {
	CallID     string
	Server     string
	Tool       string
	Data       []byte
	Cursor     int64
	NextCursor int64
	Done       bool
	TotalBytes int64
}

// PutResult persists one complete serialized MCP result for the fixed 24-hour
// retention window and returns an opaque 128-bit identifier.
func (s *Store) PutResult(ctx context.Context, server, tool string, payload []byte) (string, error) {
	var idBytes [16]byte
	if _, err := rand.Read(idBytes[:]); err != nil {
		return "", fmt.Errorf("generate result call ID: %w", err)
	}
	callID := hex.EncodeToString(idBytes[:])
	now := s.now().UTC()

	// Cleanup is deliberately opportunistic: failure to prune old rows must not
	// prevent the current complete result from being saved.
	_ = s.pruneExpired(ctx)
	if err := s.q.InsertSpoolResult(ctx, db.InsertSpoolResultParams{
		CallID:    callID,
		Server:    server,
		Tool:      tool,
		CreatedAt: formatSpoolTime(now),
		ExpiresAt: formatSpoolTime(now.Add(resultTTL)),
		Payload:   payload,
	}); err != nil {
		return "", fmt.Errorf("insert spooled result: %w", err)
	}
	return callID, nil
}

// ReadResultPage returns at most pageSize bytes using SQLite's BLOB substr
// operation, so paging never materializes the full payload in Go.
func (s *Store) ReadResultPage(ctx context.Context, callID string, cursor, pageSize int64) (ResultPage, error) {
	if cursor < 0 || pageSize <= 0 {
		return ResultPage{}, ErrResultCursorOutOfRange
	}
	row, err := s.q.PageSpoolResult(ctx, db.PageSpoolResultParams{
		CallID:   callID,
		Cursor:   cursor,
		PageSize: pageSize,
	})
	if errors.Is(err, sql.ErrNoRows) {
		return ResultPage{}, ErrResultNotFound
	}
	if err != nil {
		return ResultPage{}, fmt.Errorf("page spooled result: %w", err)
	}
	expiresAt, err := time.Parse(time.RFC3339Nano, row.ExpiresAt)
	if err != nil {
		return ResultPage{}, fmt.Errorf("parse spooled result expiry: %w", err)
	}
	if !s.now().UTC().Before(expiresAt) {
		return ResultPage{}, ErrResultExpired
	}
	if cursor > row.TotalBytes {
		return ResultPage{
			CallID:     callID,
			Server:     row.Server,
			Tool:       row.Tool,
			Cursor:     cursor,
			NextCursor: row.TotalBytes,
			Done:       true,
			TotalBytes: row.TotalBytes,
		}, ErrResultCursorOutOfRange
	}
	next := cursor + int64(len(row.Page))
	return ResultPage{
		CallID:     callID,
		Server:     row.Server,
		Tool:       row.Tool,
		Data:       row.Page,
		Cursor:     cursor,
		NextCursor: next,
		Done:       next >= row.TotalBytes,
		TotalBytes: row.TotalBytes,
	}, nil
}

func (s *Store) pruneExpired(ctx context.Context) error {
	return s.q.PruneExpiredSpoolResults(ctx, formatSpoolTime(s.now()))
}

func formatSpoolTime(value time.Time) string {
	return value.UTC().Format(spoolTimeFormat)
}

func (s *Store) runPruner() {
	defer close(s.prunerDone)
	ticker := time.NewTicker(resultPruneInterval)
	defer ticker.Stop()
	for {
		select {
		case <-s.stopPruner:
			return
		case <-ticker.C:
			_ = s.pruneExpired(context.Background())
		case done := <-s.pruneNow:
			_ = s.pruneExpired(context.Background())
			close(done)
		}
	}
}

// --- tool-call telemetry --------------------------------------------------

// CallRecord describes a single proxied tool invocation to be persisted.
type CallRecord struct {
	Server      string
	Tool        string
	Namespaced  string
	Duration    time.Duration
	Err         error
	ArgsBytes   int
	ResultBytes int
}

// estTokens is a deliberately cheap heuristic: roughly four bytes per token.
// It is good enough to compare the relative context cost of servers/tools.
func estTokens(argsBytes, resultBytes int) int64 {
	return int64((argsBytes + resultBytes) / 4)
}

// RecordCall persists one proxied tool call. Errors are swallowed into the
// returned error but never block the proxy path (callers log-and-continue).
func (s *Store) RecordCall(ctx context.Context, rec CallRecord) error {
	errStr := ""
	if rec.Err != nil {
		errStr = rec.Err.Error()
	}
	return s.q.InsertToolCall(ctx, db.InsertToolCallParams{
		Ts:          time.Now().UTC().Format(time.RFC3339Nano),
		Server:      rec.Server,
		Tool:        rec.Tool,
		Namespaced:  rec.Namespaced,
		DurationMs:  rec.Duration.Milliseconds(),
		Ok:          rec.Err == nil,
		Error:       errStr,
		ArgsBytes:   int64(rec.ArgsBytes),
		ResultBytes: int64(rec.ResultBytes),
		EstTokens:   estTokens(rec.ArgsBytes, rec.ResultBytes),
	})
}

// Totals is the all-time rollup surfaced by `mcphub stats`.
type Totals struct {
	Calls     int64 `json:"calls"`
	EstTokens int64 `json:"est_tokens"`
	TotalMs   int64 `json:"total_ms"`
	Errors    int64 `json:"errors"`
}

// allTimeCutoff is older than any real RFC3339 timestamp, so `WHERE ts >= ?`
// with it includes every row. RFC3339 strings sort lexicographically by time.
const allTimeCutoff = "0001-01-01T00:00:00Z"

// cutoff returns the RFC3339 lower bound for a lookback window. A non-positive
// duration means all time.
func cutoff(since time.Duration) string {
	if since <= 0 {
		return allTimeCutoff
	}
	return time.Now().UTC().Add(-since).Format(time.RFC3339Nano)
}

// Totals returns the all-time call count, token estimate, and error count.
func (s *Store) Totals(ctx context.Context) (Totals, error) { return s.TotalsSince(ctx, 0) }

// TotalsSince returns the rollup for calls within the last `since` window
// (0 = all time).
func (s *Store) TotalsSince(ctx context.Context, since time.Duration) (Totals, error) {
	row, err := s.q.TotalStats(ctx, cutoff(since))
	if err != nil {
		return Totals{}, err
	}
	return Totals{
		Calls:     row.Calls,
		EstTokens: asInt64(row.EstTokens),
		TotalMs:   asInt64(row.TotalMs),
		Errors:    asInt64(row.Errors),
	}, nil
}

// ServerStat is per-server usage, sorted by call count descending.
type ServerStat struct {
	Server    string `json:"server"`
	Calls     int64  `json:"calls"`
	Errors    int64  `json:"errors"`
	EstTokens int64  `json:"est_tokens"`
	AvgMs     int64  `json:"avg_ms"`
}

// ServerStats returns per-server usage statistics (all time).
func (s *Store) ServerStats(ctx context.Context) ([]ServerStat, error) {
	return s.ServerStatsSince(ctx, 0)
}

// ServerStatsSince returns per-server usage within the last `since` window.
func (s *Store) ServerStatsSince(ctx context.Context, since time.Duration) ([]ServerStat, error) {
	rows, err := s.q.ServerStats(ctx, cutoff(since))
	if err != nil {
		return nil, err
	}
	out := make([]ServerStat, 0, len(rows))
	for _, r := range rows {
		out = append(out, ServerStat{
			Server:    r.Server,
			Calls:     r.Calls,
			Errors:    asInt64(r.Errors),
			EstTokens: asInt64(r.EstTokens),
			AvgMs:     r.AvgMs,
		})
	}
	return out, nil
}

// ToolStat is per-tool usage, sorted by call count descending.
type ToolStat struct {
	Server    string `json:"server"`
	Tool      string `json:"tool"`
	Calls     int64  `json:"calls"`
	Errors    int64  `json:"errors"`
	AvgMs     int64  `json:"avg_ms"`
	EstTokens int64  `json:"est_tokens"`
}

// ToolStats returns per-tool usage statistics (all time).
func (s *Store) ToolStats(ctx context.Context) ([]ToolStat, error) {
	return s.ToolStatsSince(ctx, 0)
}

// ToolStatsSince returns per-tool usage within the last `since` window.
func (s *Store) ToolStatsSince(ctx context.Context, since time.Duration) ([]ToolStat, error) {
	rows, err := s.q.ToolCallStats(ctx, cutoff(since))
	if err != nil {
		return nil, err
	}
	out := make([]ToolStat, 0, len(rows))
	for _, r := range rows {
		out = append(out, ToolStat{
			Server:    r.Server,
			Tool:      r.Tool,
			Calls:     r.Calls,
			Errors:    asInt64(r.Errors),
			AvgMs:     r.AvgMs,
			EstTokens: asInt64(r.EstTokens),
		})
	}
	return out, nil
}

// RecentCalls returns the most recent n tool calls (newest first).
func (s *Store) RecentCalls(ctx context.Context, n int) ([]db.ToolCall, error) {
	return s.q.RecentToolCalls(ctx, int64(n))
}

// --- managed-entry bookkeeping & sync audit -------------------------------

// SetManaged replaces the full set of mcphub-managed servers for an agent. The
// clear-and-reinsert runs in a single transaction so a mid-loop failure can't
// partially wipe the owned set (which would let the next sync miss removals).
func (s *Store) SetManaged(ctx context.Context, agent string, servers []string) error {
	tx, err := s.sql.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("begin tx: %w", err)
	}
	defer tx.Rollback() // no-op after commit
	q := s.q.WithTx(tx)
	if err := q.ClearManagedForAgent(ctx, agent); err != nil {
		return fmt.Errorf("clear managed: %w", err)
	}
	now := time.Now().UTC().Format(time.RFC3339Nano)
	for _, srv := range servers {
		if err := q.UpsertManaged(ctx, db.UpsertManagedParams{Agent: agent, Server: srv, AppliedAt: now}); err != nil {
			return fmt.Errorf("upsert managed %q: %w", srv, err)
		}
	}
	return tx.Commit()
}

// ManagedFor returns the server names mcphub currently manages for an agent.
func (s *Store) ManagedFor(ctx context.Context, agent string) ([]string, error) {
	rows, err := s.q.ListManagedForAgent(ctx, agent)
	if err != nil {
		return nil, err
	}
	out := make([]string, 0, len(rows))
	for _, r := range rows {
		out = append(out, r.Server)
	}
	return out, nil
}

// LogSync appends a row to the sync audit log.
func (s *Store) LogSync(ctx context.Context, agent, mode string, servers []string, dryRun bool) error {
	return s.q.InsertSyncRun(ctx, db.InsertSyncRunParams{
		Ts:      time.Now().UTC().Format(time.RFC3339Nano),
		Agent:   agent,
		Mode:    mode,
		Servers: strings.Join(servers, ","),
		DryRun:  dryRun,
	})
}

// RecordPlanBackup remembers which backup file captured the pre-apply state
// of an agent config for a given sync plan, so --rollback <planId> can
// restore that exact backup.
func (s *Store) RecordPlanBackup(ctx context.Context, planID, agent, configPath, backupPath string) error {
	return s.q.InsertPlanBackup(ctx, db.InsertPlanBackupParams{
		PlanID:     planID,
		Agent:      agent,
		ConfigPath: configPath,
		BackupPath: backupPath,
		CreatedAt:  time.Now().UTC().Format(time.RFC3339Nano),
	})
}

// PlanBackup returns the recorded backup for a plan ID. An error wrapping
// sql.ErrNoRows means the plan was never recorded — e.g. a dry run, an apply
// that needed no backup, or a plan from before this table existed.
func (s *Store) PlanBackup(ctx context.Context, planID string) (agent, configPath, backupPath string, err error) {
	row, err := s.q.GetPlanBackup(ctx, planID)
	if err != nil {
		return "", "", "", err
	}
	return row.Agent, row.ConfigPath, row.BackupPath, nil
}

// asInt64 coerces sqlc's interface{} aggregate columns (COALESCE/SUM defeat
// its type inference under SQLite) into a plain int64. modernc returns int64
// for integer SUMs and float64 for averaged/real values; both are handled.
func asInt64(v interface{}) int64 {
	switch n := v.(type) {
	case int64:
		return n
	case int:
		return int64(n)
	case float64:
		return int64(n)
	case nil:
		return 0
	default:
		return 0
	}
}
