// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type ManagedEntry struct {
	Agent     string `json:"agent"`
	Server    string `json:"server"`
	AppliedAt string `json:"applied_at"`
}

type SyncRun struct {
	ID      int64  `json:"id"`
	Ts      string `json:"ts"`
	Agent   string `json:"agent"`
	Mode    string `json:"mode"`
	Servers string `json:"servers"`
	DryRun  bool   `json:"dry_run"`
}

type ToolCall struct {
	ID          int64  `json:"id"`
	Ts          string `json:"ts"`
	Server      string `json:"server"`
	Tool        string `json:"tool"`
	Namespaced  string `json:"namespaced"`
	DurationMs  int64  `json:"duration_ms"`
	Ok          bool   `json:"ok"`
	Error       string `json:"error"`
	ArgsBytes   int64  `json:"args_bytes"`
	ResultBytes int64  `json:"result_bytes"`
	EstTokens   int64  `json:"est_tokens"`
}
