// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const clearManagedForAgent = `-- name: ClearManagedForAgent :exec
DELETE FROM managed_entries WHERE agent = ?
`

func (q *Queries) ClearManagedForAgent(ctx context.Context, agent string) error {
	_, err := q.db.ExecContext(ctx, clearManagedForAgent, agent)
	return err
}

const deleteManaged = `-- name: DeleteManaged :exec
DELETE FROM managed_entries WHERE agent = ? AND server = ?
`

type DeleteManagedParams struct {
	Agent  string `json:"agent"`
	Server string `json:"server"`
}

func (q *Queries) DeleteManaged(ctx context.Context, arg DeleteManagedParams) error {
	_, err := q.db.ExecContext(ctx, deleteManaged, arg.Agent, arg.Server)
	return err
}

const insertSyncRun = `-- name: InsertSyncRun :exec
INSERT INTO sync_runs (ts, agent, mode, servers, dry_run) VALUES (?, ?, ?, ?, ?)
`

type InsertSyncRunParams struct {
	Ts      string `json:"ts"`
	Agent   string `json:"agent"`
	Mode    string `json:"mode"`
	Servers string `json:"servers"`
	DryRun  bool   `json:"dry_run"`
}

func (q *Queries) InsertSyncRun(ctx context.Context, arg InsertSyncRunParams) error {
	_, err := q.db.ExecContext(ctx, insertSyncRun,
		arg.Ts,
		arg.Agent,
		arg.Mode,
		arg.Servers,
		arg.DryRun,
	)
	return err
}

const insertToolCall = `-- name: InsertToolCall :exec
INSERT INTO tool_calls (
    ts, server, tool, namespaced, duration_ms, ok, error, args_bytes, result_bytes, est_tokens
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertToolCallParams struct {
	Ts          string `json:"ts"`
	Server      string `json:"server"`
	Tool        string `json:"tool"`
	Namespaced  string `json:"namespaced"`
	DurationMs  int64  `json:"duration_ms"`
	Ok          bool   `json:"ok"`
	Error       string `json:"error"`
	ArgsBytes   int64  `json:"args_bytes"`
	ResultBytes int64  `json:"result_bytes"`
	EstTokens   int64  `json:"est_tokens"`
}

func (q *Queries) InsertToolCall(ctx context.Context, arg InsertToolCallParams) error {
	_, err := q.db.ExecContext(ctx, insertToolCall,
		arg.Ts,
		arg.Server,
		arg.Tool,
		arg.Namespaced,
		arg.DurationMs,
		arg.Ok,
		arg.Error,
		arg.ArgsBytes,
		arg.ResultBytes,
		arg.EstTokens,
	)
	return err
}

const listManagedForAgent = `-- name: ListManagedForAgent :many
SELECT agent, server, applied_at FROM managed_entries WHERE agent = ? ORDER BY server
`

func (q *Queries) ListManagedForAgent(ctx context.Context, agent string) ([]ManagedEntry, error) {
	rows, err := q.db.QueryContext(ctx, listManagedForAgent, agent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManagedEntry{}
	for rows.Next() {
		var i ManagedEntry
		if err := rows.Scan(&i.Agent, &i.Server, &i.AppliedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentSyncRuns = `-- name: RecentSyncRuns :many
SELECT id, ts, agent, mode, servers, dry_run FROM sync_runs ORDER BY id DESC LIMIT ?
`

func (q *Queries) RecentSyncRuns(ctx context.Context, limit int64) ([]SyncRun, error) {
	rows, err := q.db.QueryContext(ctx, recentSyncRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncRun{}
	for rows.Next() {
		var i SyncRun
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Agent,
			&i.Mode,
			&i.Servers,
			&i.DryRun,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentToolCalls = `-- name: RecentToolCalls :many
SELECT id, ts, server, tool, namespaced, duration_ms, ok, error, args_bytes, result_bytes, est_tokens FROM tool_calls ORDER BY id DESC LIMIT ?
`

func (q *Queries) RecentToolCalls(ctx context.Context, limit int64) ([]ToolCall, error) {
	rows, err := q.db.QueryContext(ctx, recentToolCalls, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ToolCall{}
	for rows.Next() {
		var i ToolCall
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Server,
			&i.Tool,
			&i.Namespaced,
			&i.DurationMs,
			&i.Ok,
			&i.Error,
			&i.ArgsBytes,
			&i.ResultBytes,
			&i.EstTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const serverStats = `-- name: ServerStats :many
SELECT
    server,
    COUNT(*)                                      AS calls,
    COALESCE(SUM(CASE WHEN ok THEN 0 ELSE 1 END), 0) AS errors,
    COALESCE(SUM(est_tokens), 0)                  AS est_tokens,
    CAST(COALESCE(AVG(duration_ms), 0) AS INTEGER)   AS avg_ms
FROM tool_calls
WHERE ts >= ?1
GROUP BY server
ORDER BY calls DESC
`

type ServerStatsRow struct {
	Server    string      `json:"server"`
	Calls     int64       `json:"calls"`
	Errors    interface{} `json:"errors"`
	EstTokens interface{} `json:"est_tokens"`
	AvgMs     int64       `json:"avg_ms"`
}

func (q *Queries) ServerStats(ctx context.Context, since string) ([]ServerStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, serverStats, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServerStatsRow{}
	for rows.Next() {
		var i ServerStatsRow
		if err := rows.Scan(
			&i.Server,
			&i.Calls,
			&i.Errors,
			&i.EstTokens,
			&i.AvgMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toolCallStats = `-- name: ToolCallStats :many
SELECT
    server,
    tool,
    COUNT(*)                                      AS calls,
    COALESCE(SUM(CASE WHEN ok THEN 0 ELSE 1 END), 0) AS errors,
    CAST(COALESCE(AVG(duration_ms), 0) AS INTEGER)   AS avg_ms,
    COALESCE(SUM(est_tokens), 0)                  AS est_tokens
FROM tool_calls
WHERE ts >= ?1
GROUP BY server, tool
ORDER BY calls DESC
`

type ToolCallStatsRow struct {
	Server    string      `json:"server"`
	Tool      string      `json:"tool"`
	Calls     int64       `json:"calls"`
	Errors    interface{} `json:"errors"`
	AvgMs     int64       `json:"avg_ms"`
	EstTokens interface{} `json:"est_tokens"`
}

func (q *Queries) ToolCallStats(ctx context.Context, since string) ([]ToolCallStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, toolCallStats, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ToolCallStatsRow{}
	for rows.Next() {
		var i ToolCallStatsRow
		if err := rows.Scan(
			&i.Server,
			&i.Tool,
			&i.Calls,
			&i.Errors,
			&i.AvgMs,
			&i.EstTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalStats = `-- name: TotalStats :one
SELECT
    COUNT(*)                          AS calls,
    COALESCE(SUM(est_tokens), 0)      AS est_tokens,
    COALESCE(SUM(duration_ms), 0)     AS total_ms,
    COALESCE(SUM(CASE WHEN ok THEN 0 ELSE 1 END), 0) AS errors
FROM tool_calls
WHERE ts >= ?1
`

type TotalStatsRow struct {
	Calls     int64       `json:"calls"`
	EstTokens interface{} `json:"est_tokens"`
	TotalMs   interface{} `json:"total_ms"`
	Errors    interface{} `json:"errors"`
}

func (q *Queries) TotalStats(ctx context.Context, since string) (TotalStatsRow, error) {
	row := q.db.QueryRowContext(ctx, totalStats, since)
	var i TotalStatsRow
	err := row.Scan(
		&i.Calls,
		&i.EstTokens,
		&i.TotalMs,
		&i.Errors,
	)
	return i, err
}

const upsertManaged = `-- name: UpsertManaged :exec
INSERT INTO managed_entries (agent, server, applied_at)
VALUES (?, ?, ?)
ON CONFLICT(agent, server) DO UPDATE SET applied_at = excluded.applied_at
`

type UpsertManagedParams struct {
	Agent     string `json:"agent"`
	Server    string `json:"server"`
	AppliedAt string `json:"applied_at"`
}

func (q *Queries) UpsertManaged(ctx context.Context, arg UpsertManagedParams) error {
	_, err := q.db.ExecContext(ctx, upsertManaged, arg.Agent, arg.Server, arg.AppliedAt)
	return err
}
